/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <hamsandwich>
#include <fun>


#define PLUGIN "ADMIN_HACKER_DETECTOR"
#define VERSION "1.0"
#define AUTHOR "alex rafael"


public plugin_init() 
{
	register_plugin(PLUGIN, VERSION, AUTHOR)
	register_clcmd("say /teste", "FwdHamPlayerSpawn")
    register_clcmd("say /admin", "showmenu")
	RegisterHam( Ham_Spawn, "player", "FwdHamPlayerSpawn", 1 );
}


public FwdHamPlayerSpawn(id)
{
	//ExecuteHamB( Ham_CS_RoundRespawn, id ) 
	set_user_rendering(id,kRenderFxNone,0,0,0,kRenderTransAlpha,1) 
    set_user_footsteps(id)
}

public showmenu( id )
{

    new menu = menu_create( "^n^n^n\y[ Admin_hacker detector ] \wjogadores?", "submenu" );

    new players[ 32 ], pnum, tempid;
    new szName[ 32 ], szTempid[ 10 ];

    get_players( players, pnum, "" );

    for( new i; i< pnum; i++ )
    {
    tempid = players[ i ];



    get_user_name( tempid, szName, 31 );
    num_to_str( tempid, szTempid, 9 );
    menu_additem( menu, szName, szTempid, 0 );
}

    menu_display( id, menu );
    return PLUGIN_HANDLED;
}


public submenu( const id, const menu, const item )
{
    if( item == MENU_EXIT )
    {
    menu_destroy( menu );
    return // PLUGIN_HANDLED;
}

    new data[ 6 ], iName[ 64 ];
    new access, callback;
    menu_item_getinfo( menu, item, access, data,5, iName, 63, callback );

    new tempid = str_to_num( data );

         
    if(tempid )
    {

        
    }
   
}

 



